remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jemoji
markdown: kramdown
kramdown:
    math_engine: katex

title: Apunts GEI
description: Apunts del Grau en Enginyeria Inform√†tica de la UPC
